In [1]:
# Importando as bibliotecas necessárias
import pandas as pd

In [35]:
# Importando a base de dados
df = pd.read_csv('data/Superstore.csv',encoding='latin1')
df_vendas = df.copy()
df_calendar = pd.read_csv('data/calendar.csv')

# ['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode','Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State','Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category','Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

# Nomes das colunas em português
# ['ID da Linha', 'ID do Pedido', 'Data do Pedido', 'Data de Envio', 'Modo de Envio','ID do Cliente', 'Nome do Cliente', 'Segmento', 'País', 'Cidade', 'Estado','CEP', 'Região', 'ID do Produto', 'Categoria', 'Subcategoria','Nome do Produto', 'Vendas', 'Quantidade', 'Desconto', 'Lucro']

display(df_vendas.head(5))

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,09-11-2013,12-11-2013,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,13-06-2013,17-06-2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,11-10-2012,18-10-2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
display(df_vendas.info())
display(df_vendas.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

None

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [36]:
# Removendo colunas que não serão úteis
#df_vendas = df_vendas.drop(columns=['Row ID'])

# alterando o tipo da coluna
df_vendas['Ship Date'] = pd.to_datetime(df_vendas['Ship Date'],format='%d-%m-%Y')
df_vendas['Order Date'] = pd.to_datetime(df_vendas['Order Date'], format='%d-%m-%Y')

df_calendar['Order Date'] = pd.to_datetime(df_vendas['Order Date'], format='%d-%m-%Y')

In [37]:
# Criando colunas

"""
- Os valores da coluna Sales já estão com o desconto (Discount) aplicado.
- A coluna total_cost já inclui o desconto (Sales) embutido, então ela reflete o custo por unidade vendida na transação, não necessariamente o custo de aquisição do produto em si, que seria fixo independente do desconto.

"""

# Preço unitário
df_vendas['unit_price'] = df_vendas['Sales'] / (df_vendas['Quantity'] * (1 - df_vendas['Discount']))
# Venada sem desconto
df_vendas['sale_without_discount'] = df_vendas['unit_price'] * df_vendas['Quantity']

# Custo total
df_vendas['total_cost'] = df_vendas['Sales'] - df_vendas['Profit']
# Custo unitário
df_vendas['unit_cost'] = df_vendas['total_cost'] / df_vendas['Quantity']

In [ ]:
# Juntando as bases

df_base_completa = df_vendas.merge(df_calendar, on='Order Date')
df_base_completa = df_base_completa.sort_values(by=['year','Month_num', 'Order Date'])

display(df_base_completa)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Profit,unit_price,sale_without_discount,total_cost,unit_cost,year,Month_num,Month_name,Season,type_day
104099,7981,CA-2011-103800,2011-01-04,2011-01-08,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,5.5512,10.28,20.56,10.8968,5.4484,2011,1,January,Winter,working day
10630,740,CA-2011-112326,2011-01-05,2011-01-09,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,4.2717,4.91,14.73,7.5123,2.5041,2011,1,January,Winter,working day
10631,740,CA-2011-112326,2011-01-05,2011-01-09,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,4.2717,4.91,14.73,7.5123,2.5041,2011,1,January,Winter,working day
10632,740,CA-2011-112326,2011-01-05,2011-01-09,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,4.2717,4.91,14.73,7.5123,2.5041,2011,1,January,Winter,working day
10633,741,CA-2011-112326,2011-01-05,2011-01-09,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,-64.7748,113.64,340.92,337.5108,112.5036,2011,1,January,Winter,working day
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67079,5092,CA-2014-156720,2014-12-31,2015-01-04,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,-0.6048,1.26,3.78,3.6288,1.2096,2014,12,December,Winter,working day
67080,5092,CA-2014-156720,2014-12-31,2015-01-04,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,-0.6048,1.26,3.78,3.6288,1.2096,2014,12,December,Winter,working day
67081,5092,CA-2014-156720,2014-12-31,2015-01-04,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,-0.6048,1.26,3.78,3.6288,1.2096,2014,12,December,Winter,working day
67082,5092,CA-2014-156720,2014-12-31,2015-01-04,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,-0.6048,1.26,3.78,3.6288,1.2096,2014,12,December,Winter,working day
67083,5092,CA-2014-156720,2014-12-31,2015-01-04,Standard Class,JM-15580,Jill Matthias,Consumer,United States,Loveland,...,-0.6048,1.26,3.78,3.6288,1.2096,2014,12,December,Winter,working day